# Generated by Django 6.0 on 2025-12-29 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 29, 5, 33, 52, 885157)),
        ),
    ]
