# Generated by Django 6.0 on 2025-12-29 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_bill_products_alter_bill_date_buyproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 29, 5, 46, 23, 130714)),
        ),
    ]
